
###############
# users
###############

### list

GET http://localhost:9999/users

#### with query params

GET http://localhost:9999/users?_start=1&_end=3&_order=ASC&_sort=name

### get detail by id

GET http://localhost:9999/users/3

### delete by id

DELETE http://localhost:9999/users/9

### update by id

PUT http://localhost:9999/users/3
content-type: application/json

{
  "id": 3,
  "name": "NEW NAME",
  "username": "Karianne",
  "email": "Julianne.OConner@kory.org",
  "address": {
    "street": "Hoeger Mall",
    "suite": "Apt. 692",
    "city": "South Elvis",
    "zipcode": "53919-4257",
    "geo": { "lat": "29.4572", "lng": "-164.2990" }
  },
  "phone": "493-170-9623 x156",
  "website": "kale.biz",
  "company": {
    "name": "Robel-Corkery",
    "catchPhrase": "Multi-tiered zero tolerance productivity",
    "bs": "transition cutting-edge web services"
  }
}

###############
# posts
###############

### list
GET http://localhost:9999/posts

#### with query params

GET http://localhost:9999/posts?_start=1&_end=3&_order=DESC&_sort=title

### get detail by id

GET http://localhost:9999/posts/3

### delete by id

DELETE http://localhost:9999/posts/3

### update by id

PUT http://localhost:9999/posts/3
content-type: application/json

{
  "id": 3,
  "userId": 3,
  "title": "A edited title",
  "body": "A edited body"
}

### New create

POST http://localhost:9999/posts
content-type: application/json

{
  "userId": 3,
  "title": "A new title",
  "body": "A new body"
}

###################################
# original
###################################

### users
GET http://jsonplaceholder.typicode.com/users?_end=25&_order=ASC&_sort=id&_start=0

### update user by id
PUT http://jsonplaceholder.typicode.com/users/1
content-type: application/json

{
  "id": 3,
  "name": "NEW NAME",
  "username": "Karianne",
  "email": "Julianne.OConner@kory.org",
  "address": {
    "street": "Hoeger Mall",
    "suite": "Apt. 692",
    "city": "South Elvis",
    "zipcode": "53919-4257",
    "geo": { "lat": "29.4572", "lng": "-164.2990" }
  },
  "phone": "493-170-9623 x156",
  "website": "kale.biz",
  "company": {
    "name": "Robel-Corkery",
    "catchPhrase": "Multi-tiered zero tolerance productivity",
    "bs": "transition cutting-edge web services"
  }
}

### posts
GET http://jsonplaceholder.typicode.com/posts?_end=35&_order=ASC&_sort=id&_start=0
